# Generated by Django 2.1.5 on 2019-02-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
    ]
